name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make build-essential g++ clang autoconf javacc patchelf openjdk-8-jdk maven m4 tar lzip libfftw3-dev

    - name: Build FHE libraries
      run: |
        chmod +x .ci_lib.sh
        ./.ci_lib.sh

    - name: Build T2
      run: sbt buildT2

    - name: run basicTest
      env:
        FHETEST_HOME: ${{ github.workspace }}
      run: |
        sbt basicTest
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check code format
      run: sbt formatCheck
