name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make build-essential g++ clang autoconf javacc patchelf openjdk-8-jdk maven m4 tar lzip libfftw3-dev

    - name: Build FHELibs
      run: sbt buildFHElibs

    - name: Build T2
      run: sbt buildT2

    - name: run backendTest
      env:
        FHETEST_HOME: ${{ github.workspace }}
      run: sbt backendTest